const listaDeAutosJSON = [
    {
        "_id": 1,
        "foto": "ram1500.jpg",
        "nombre": "Ram 1500",
        "descripcion": "Laramie 5.7 4x4 C/D",
        "anio": 2014,
        "kilometraje": 104000,
        "precio": 35900000,
    },
    {
        "_id": 2,
        "foto": "audiq3.jpg",
        "nombre": "Audi Q3",
        "descripcion": "1.4T Sport 150cv",
        "anio": 2019,
        "kilometraje": 26000,
        "precio": 34900000,
    },
    {
        "_id": 3,
        "foto": "fiattoro.jpg",
        "nombre": "Fiat Toro",
        "descripcion": "Volcano 2.0TDI 4x4 AT Pack Premium",
        "anio": 2017,
        "kilometraje": 110000,
        "precio": 22900000,
    },
    {
        "_id": 4,
        "foto": "renaultkangoo.jpg",
        "nombre": "Renalut Kangoo",
        "descripcion": "Express 1.6 Confort SCE (L18)",
        "anio": 2024,
        "kilometraje": 0,
        "precio": 21900000,
    },
    {
        "_id": 5,
        "foto": "chevroletmontana.jpg",
        "nombre": "Chevrolet Montana",
        "descripcion": "LTZ 1.2 T AT6 (L23)",
        "anio": 2024,
        "kilometraje": 0,
        "precio": 30900000,
    },
];